Fix ridge regression when no selected_features
When there is no selected_features, X = table[selected_features, :]
used to raise :
"Empty selections are not allowed (axis %d)" % idx)
IndexError: Empty selections are not allowed (axis 0)
From now on, if there no selected_features for a given task,
ridge regression is not run, and predictions are NA for each train indices.